name: trigger-ghrs-via-label
on:
  pull_request:
    types: [labeled]

jobs:
  j1:
    name: Trigger GHRS run via applying a label
    runs-on: ubuntu-latest
    steps:
      - name: trigger
        if: github.event.label.name == 'run-ghrs'
        env:
          GCS_SVC_ACC_JSON: ${{ secrets.ghrs_gcs_svc_acc_json }}
        uses: jgehrcke/github-repo-stats@HEAD
